### ISSUE TITLE
to use

### ISSUE THREAD

**Issue by purarue** [seanbreckenridge/poly-project-euler#1]
## To Use/Try to Use

- [x] [smalltalk](https://learnxinyminutes.com/docs/smalltalk/)
- [x] [crystal](https://learnxinyminutes.com/docs/crystal/)
- [x] [nim](https://learnxinyminutes.com/docs/nim/)
- [x] [OCaml](https://learnxinyminutes.com/docs/ocaml/)
- [x] [racket](https://learnxinyminutes.com/docs/racket/)
- [x] typescript

**Comment by purarue** [comment]
## To Not Use

Tried to implement a problem in these and didnt finish

* pascal
* fortran
* cobol
* R
* objective-c
* assembly (not great at it)
* SQL (imperative programming here isnt fun)
* simula (lots of interesting ideas, I just dont want to implement aspects of an ancient stdlib)
* dylan; couldnt wrap my head around the tooling/structure

---

Dont want to use for one reason or another (not applicable/seem to be similar to old ones Ive tried above)

* object pascal/delphi
* ada
* algol 60/algol 68
* VBasic (VBScript)
* ABAP/SAS

---

Already used very similar languages

* Alice (already did ML)
* hack (already used PHP)
* MATLAB (already used GNU Octave; also, proprietary)

**Comment by seanbreckenridge** [comment]
Others to consider (Copied from TIOBE 50-100)

- [ ] Crystal
- [ ] Dylan
- [ ] Nim

From: [learnxinyminutes](https://learnxinyminutes.com/)

- [ ] [OCaml](https://learnxinyminutes.com/docs/ocaml/)
- [ ] [PureScript](https://learnxinyminutes.com/docs/purescript/)

**Comment by seanbreckenridge** [comment]
try https://en.wikipedia.org/wiki/APL_(programming_language)
